### ISSUE TITLE
Not working on OpenWrt 21.02

### ISSUE THREAD

**Issue by People-11** [scutclient/scutclient#19]
Fri Jan 18 17:18:18 2013 daemon.info scutclient[3581]: [2013-01-18 17:18:18][ALL  ][INF]:[scutclient built at: Jun  1 2021 01:58:08]
Fri Jan 18 17:18:18 2013 daemon.info scutclient[3581]: [2013-01-18 17:18:18][ALL  ][INF]:[Authored by Scutclient Project]
Fri Jan 18 17:18:18 2013 daemon.info scutclient[3581]: [2013-01-18 17:18:18][ALL  ][INF]:[Source code available at https://github.com/scutclient/scutclient]
Fri Jan 18 17:18:18 2013 daemon.info scutclient[3581]: [2013-01-18 17:18:18][ALL  ][INF]:[Contact us with QQ group 262939451]
Fri Jan 18 17:18:18 2013 daemon.info scutclient[3581]: [2013-01-18 17:18:18][ALL  ][INF]:[#######################################]
Fri Jan 18 17:18:18 2013 daemon.info scutclient[3581]: [2013-01-18 17:18:18][INIT ][ERROR]:[ioctl get if_flag error: No such device]
Fri Jan 18 17:18:18 2013 daemon.info scutclient[3581]: [2013-01-18 17:18:18][8021X][ERROR]:[Unable to initialize 802.1x socket.]

**Comment by People-11** [comment]
On OpenWrt 21.02.0-rc2 r16122-c2139eef27 r0-d593b38

**Comment by People-11** [comment]
使用 scutclient --username <username> --password <password> [options...] 命令可正常启动
使用 /etc/init.d/scutclient start 命令则出现以上错误

**Comment by 981213** [comment]
FYI: https://openwrt.org/releases/21.02/notes-21.02.0-rc2
网络配置格式大改…启动脚本获取接口名称的地方需要作相应调整

**Comment by People-11** [comment]
暂时的解决办法：
在/etc/新建.sh，里面写上scutclient --username --password [options...] 命令并chmod 0777
在crontab中 10 6 * * 1-5 /etc/scutclient.sh &

**Comment by xingyunjohn1** [comment]
> 暂时的解决办法：
> 在/etc/新建.sh，里面写上scutclient --username --password [options...] 命令并chmod 0777
> 在crontab中 10 6 * * 1-5 /etc/scutclient.sh &

Crontab计划任务并不完美（如日间意外断电重启）
可以考虑使用开机启动脚本？

**Comment by jimstar06** [comment]
由于21.02引入DSA，原有的 ifname 被移除，改为 device。
为保证旧版兼容性，先读取 network.wan.ifname ，若读取失败则读取 network.wan.device 。
临时 workaround 可将 /etc/init/scutclient 中的 ifname 替换为 device 即可。
Release Notes包含[示例](https://openwrt.org/releases/21.02/notes-21.02.0#new_uci_syntax)

**Comment by 981213** [comment]
fixed with 46dd584
