### ISSUE TITLE
Add windows support plz?

### ISSUE THREAD

**Issue by WinterOfBit** [scutclient/scutclient#25]
Just wanna connect via cli qwq.

**Comment by 981213** [comment]
Why...?

This client is implemented using Linux raw socket, so it can't be ported to windows unless someone is willing to rewrite the entire 802.1x authentication part using libpcap.

**Comment by WinterOfBit** [comment]
> 

I'm trying Windows Server. And I also want to use this on my personal computer for the 1.0 Gig spped interface configuration is not supported by the official DrClient version (>_<). 
So I guess I'd better try some other way. 🥺＞﹏＜

(我也不知道为啥开issue的时候没说中文 = =

**Comment by 981213** [comment]
2333
不过千兆网口不支持是什么情况 我在国际校区的时候用的就是千兆网来着
学校的客户端倒是有一个比较蠢的地方：它不会指定UDP认证数据包的发送接口，所以你不能同时连着别的网络，比如wifi什么的

**Comment by WinterOfBit** [comment]
大学城，貌似没有同时用了wifi（？，usb3.0转ri45的，强制设定1G后DrClient记录找不到认证服务器，dns也失效了= =

**Comment by 981213** [comment]
大学城宿舍的交换机就是百兆的你强制千兆没用啊

**Comment by WinterOfBit** [comment]
0.0啊这样吗，之前看到有人下载上过100MB/s才想试试的，那寄掉力＞﹏＜

**Comment by 981213** [comment]
貌似只用国际校区和五山北区那栋新楼是千兆的 233

**Comment by cq01** [comment]
https://github.com/SeaLoong/drcom4scut 试试这个？
