### ISSUE TITLE
[8021X][ERROR]:[Unable to create raw socket: Operation not permitted]

### ISSUE THREAD

**Issue by zahir-w** [scutclient/scutclient#26]
I dont know how to solve this problem when run the scutclient.
![Screenshot from 2023-04-22 00-47-23](https://user-images.githubusercontent.com/55045841/233695202-a6612de7-b117-42e7-9b84-8684676439db.png)

**Comment by 981213** [comment]
This program needs to be run as root.
Alternatively you can add CAP_NET_ADMIN and CAP_NET_RAW to the executable using setcap.
