### ISSUE TITLE
Hash值似乎已经过期

### ISSUE THREAD

**Issue by DynamicLoader** [scutclient/scutclient#27]
如题，使用 master 分支自行编译，能登陆但是过一段时间就会掉，而且是变成无连接的那种。

从另外一个端找到了一个hash能用。请问hash值是以何种算法计算出来的呢？

谢谢。

**Comment by 981213** [comment]
Hash是直接使用校园网客户端抓认证时的包得到的，并非计算值。

**Comment by 981213** [comment]
具体可以参考源代码中对hash参数的使用，印象中是认证过程中某个包的明文内容。

**Comment by 981213** [comment]
目前最新版的Windows客户端的Hash是这个：6047225a1aa8df1c02995bdd6ee2c42b6f444a1a
在客户端安装目录的日志里面有
