### ISSUE TITLE
建议对应每个版本 release ipk 文件

### ISSUE THREAD

**Issue by emdoe** [scutclient/scutclient#3]
@forward619 是否方便发一下新的 scutclient_1.6_ar71xx.ipk 以及其他 ipk 文件？方便断网的时候手动更新，感谢！

**Comment by forward619** [comment]
各版本的ipk均发布在华工路由器正式群，这里只是发布源码，不会预编译ipk放这里的

**Comment by emdoe** [comment]
是否方便解释一下这样做的目的？

**Comment by zhchan** [comment]
@emdoe 如果你是华工的，你可以加群直接用；如果你不是，看看代码就好；如果你会编译，那你还伸手干什么？哈哈哈哈哈哈搞笑

**Comment by emdoe** [comment]
@zhchan 编译起来自然不是难事，但当时在学校断网情况下自然无法下载 openwrt 的包去做编译，跑到外面蹭网下载再编译是很麻烦的事情，并且，我并不认为这种情况很搞笑。所以，我的 issue 提及的是宏观上希望 release ipk 文件，下方才说明我具体希望的版本，望理解。

**Comment by zhchan** [comment]
@emdoe 我来给你继续解释。
1. 首先你需要能正常上网才能说用路由的事情。正常可以上网的话，下点东西很难吗？你上不了网你舍友呢？图书馆，食堂，公共区域的scut无线网络可以上不？
2. 即便是学校更新了，我们不可能第一时间马上更新代码，那在这等待期间你还要不要上网了？是不是还是得用有线拨号过度一段日子呢？
3. 请问，放在github和放在qq群有区别吗大帅哥？反正都要上网下载。是不是放在github就可以用玄学下载了？

**Comment by zhchan** [comment]
@emdoe 至少我觉得传了qq群再传github是件很麻烦的事。这个解释满意了吗？
