### ISSUE TITLE
how to update scutclient？

### ISSUE THREAD

**Issue by RebornL** [scutclient/scutclient#9]
Now I use the scutclient for lede found in the router group，but i feel it‘s easy to go offline.So I want to find the update way for scutclient. Thanks!

**Comment by libc0607** [comment]
Hi if you want to try the latest release please see 'dev_rebase' branch.
You can follow the instructions in readme.md to compile. 
If you find any bugs please open an issue or find us in the router group.

**Comment by RebornL** [comment]
Thanks! I will try.
